### ISSUE TITLE
Portal crash on safari

### ISSUE THREAD

**Issue by boriside** [Rostlab/JS16_ProjectF#396] opened 2016-04-11 13:15 UTC
For those who don't believe me I created a video :D The site crashes on regular mac computers on safari only. Tested on 4 machines.
[https://drive.google.com/open?id=0B64iNLTxwWNPS0FnNGJpUGdJdHM](https://drive.google.com/open?id=0B64iNLTxwWNPS0FnNGJpUGdJdHM)

**Comment by jorjo1** [comment] 2016-04-11 13:36
lol bring me an apple product to test

**Comment by mammuth** [comment] 2016-04-11 18:53
Can't reproduce on El Capitan and Safari 9.0

**Comment by mammuth** [comment] 2016-04-11 18:53
Same as with your mobile devices: Can you make sure nothing at your network is blocking something?

**Comment by boriside** [comment] 2016-04-12 06:56
Yes, but it's not my internet. Maybe the internet of the Uni. It happens only on safary on Mac.

**Comment by sacdallago** [comment] 2016-04-12 07:36
This time I can confirm! Happens to me as well, am also behind the LRZ network though.

The error only seems to happen if I scroll **right** after the page loads, if I wait one/two second/s it doesn't happen

**Comment by jorjo1** [comment] 2016-04-12 18:04
@sacdallago can you look thru your network logs and tell us what happens then?

**Comment by sacdallago** [comment] 2016-04-12 20:04
Tomorrow afternoon :D I just got home and I'm busy from 8 to 16 tomorrow, no lunch break.. It's awful being a full time procrastinator :joy:

**Comment by togiberlin** [comment] 2016-04-13 20:14
I can confirm, OS X El Capitan v10.11.4 with Safari 9.1

**Comment by sacdallago** [comment] 2016-04-13 20:17
@jorjo1 @mammuth @yashha I think solving #369 will solve this one too! Please start working on that issue if you can :)

**Comment by sacdallago** [comment] 2016-04-13 21:18
Done some further testing: Only happens on home page. Must definitely be a component of that. Would make sense to selectively turn off components and see whether the problem still occurs.

If you need macs for testing, come to rostlab

**Comment by yashha** [comment] 2016-04-13 21:19
Is there anything in the console when this is happening?

**Comment by yashha** [comment] 2016-04-13 21:20
Or and requests that fail?
Maybe no bundle.js included or sth like that?

**Comment by sacdallago** [comment] 2016-04-13 21:21
I can't test the console if safari crashes :(

**Comment by yashha** [comment] 2016-04-13 21:23
Safari crashes completely? :O

**Comment by sacdallago** [comment] 2016-04-13 21:23
From the crash I get:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
```

But that's not very informative! Apart that you managed to try to access a non-user-space address :D

**Comment by sacdallago** [comment] 2016-04-13 21:26
@yashha sort of! The thread for that page crashes, but ever since they introduced separate threads for separate pages (like chrome) the whole-whole app is much harder to bring down. But you still managed to do something I had never seen happening before! :D

**Comment by yashha** [comment] 2016-04-13 21:33
The other pages of the site don't crash?

**Comment by sacdallago** [comment] 2016-04-13 21:36
Nope

**Comment by yashha** [comment] 2016-04-13 21:38
Maybe I have a fix.
We should try it asap.
Edit: No, probably not a fix

**Comment by yashha** [comment] 2016-04-13 21:45
Maybe this is a fix for this issue but probably not.
https://github.com/Rostlab/JS16_ProjectF/pull/430

**Comment by sacdallago** [comment] 2016-04-13 21:45
I ~~merged but~~ have some questions on the PR

**Comment by sacdallago** [comment] 2016-04-14 08:58
@yashha your fix hasn't made it to develop. I have messed up a little too much with the PRs I fear... Need to go to a meeting now, will check it later! Sorry

**Comment by sacdallago** [comment] 2016-04-14 11:50
This should be fixed

**Closed as completed by sacdallago** 2016-04-14 11:50 UTC
Labels: bug
