### ISSUE TITLE
Issue with build

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#203] opened 2016-03-30 12:28 UTC
https://travis-ci.org/Rostlab/JS16_ProjectF/builds/119496162

**Comment by gyachdav** [comment] 2016-03-30 13:17
Do you guys have an E representative for your project?

Shouldn't they take care of all your build and config issues?

@sacdallago please intervene and assign someone to take care of all test,build,deploy issues that F is having.

**Comment by yashha** [comment] 2016-03-30 13:35
I thought that partly my job because I set it up, but we have one @TheZoker is doing testing for us. Rostlab/JS16_ProjectE#19

**Comment by gyachdav** [comment] 2016-03-30 13:36
@yashha you need to learn to delegate :smile: 

Make sure to involve @TheZoker as much as possible

**Comment by TheZoker** [comment] 2016-03-30 16:59
Yes I'm here to help!
The issue is closed, so is this fixed?

**Comment by sacdallago** [comment] 2016-03-30 17:00
:D Apparently I still assigned you just in case

**Comment by TheZoker** [comment] 2016-03-30 17:01
Yes that's good :)
I currently try to understand, what was the issue here: https://github.com/Rostlab/JS16_ProjectF/commit/1f33dc2ec3d4accd6bbe9e43d4abf54da5f46206

Seems like a valid package.json to me :confused:

**Comment by yashha** [comment] 2016-03-30 17:07
I think the problem was the some dependecies were not loading
But i don't know :)
I changed it to this and now it works

**Comment by sacdallago** [comment] 2016-03-30 17:10
actually not separating devDependencies and dependencies is pretty, pretty bad practice.

Try to figure out if you can sort this out without resorting on patches @TheZoker please

**Comment by TheZoker** [comment] 2016-03-30 18:47
Ok I contacted the travis support, hopefully I get an answer soon.

**Comment by TheZoker** [comment] 2016-04-01 20:37
I got a answer, but no solution yet. I will keep you up2date

**Comment by gyachdav** [comment] 2016-04-01 21:24
@TheZoker  Status? can this be closed?

**Comment by TheZoker** [comment] 2016-04-01 21:26
No not yet, because travis fails, if we undo this change. I'm in contact with the Travis support and we hopefully find the issue.

**Comment by sacdallago** [comment] 2016-04-01 22:50
:D that's some high-end tech support and testing! Nice job

**Comment by TheZoker** [comment] 2016-04-08 15:27
@sacdallago Seems Dominic from travis found the issue:

>  I think I know the problem. You have the following environment variable defined in your repo settings:
> $ export NODE_ENV=production
> This variable is picked up by NPM and from [the documentation](https://docs.npmjs.com/cli/install):
> With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.
> Travis CI doesn't transfer environment variable in pull requests originating from forks. Hence, this explains why the build succeeded in my pull request i.e. the NODE_ENV environment variable wasn't defined in my build and the html-webpack-plugin module was properly installed from the "devDependencies" section of the package.json file.
> That being said, you might want to review if you need this environment variable or keep the html-webpack-plugin module in your "dependencies" section of your package.json file.

**Comment by TheZoker** [comment] 2016-04-08 23:19
@mammuth @jorjo1 @mina-zaki @yashha @Andrew094 Guys I need to know, which of the [dependencies](https://github.com/Rostlab/JS16_ProjectF/blob/develop/package.json#L21) are real devDependencies, so they are not used in the main app, but for testing, linting etc.

Can you please list me these packages? I guess you know your packages best :)

**Comment by yashha** [comment] 2016-04-08 23:24
I think only 

```
"webpack-dev-middleware": "^1.6.1",
"webpack-dev-server": "^1.14.1",
"webpack-hot-middleware": "^2.10.0"
```

They are not neccecary in 
npm run build or npm run serve

**Comment by TheZoker** [comment] 2016-04-08 23:29
What about things like:

``````
"csslint": "^0.10.0",
"csslint-loader": "^0.2.1",
"eslint": "^2.2.0",
"eslint-loader": "^1.3.0",
"eslint-plugin-react": "^4.1.0",```
``````

**Comment by yashha** [comment] 2016-04-08 23:31
They're used in the build process, to test while building in travis.
It would be probably better to have a separate testing env but its ok so I think.

**Comment by TheZoker** [comment] 2016-04-09 00:09
Should be fixed with #344

**Closed as completed by TheZoker** 2016-04-09 00:09 UTC
Labels: bug
