### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#524] opened 2016-06-25 18:24 UTC
Christian, please take a look :)

**Comment by sacdallago** [comment] 2016-06-25 19:52
?

There's some funny behavior, but it's up to me

**Comment by yashha** [comment] 2016-06-25 20:29
strange, black screen for me
![image](https://cloud.githubusercontent.com/assets/4728786/16358981/4d52640a-3b24-11e6-921d-b3ea845b6adb.png)

**Comment by sacdallago** [comment] 2016-06-25 21:09
I now know where the issue is, thanks.

This is unfortunately out of my power to fix. Most likely it's going to be fixed on Monday by the guy who set me up with the VM. It's a shame that since the problem a month ago everything seems to be going sideways... But it's really not up to me ;)

Best,
C

**Comment by gyachdav** [comment] 2016-06-26 09:42
Works for me on the laptop but on mobile I'm getting a dark screen.

**Comment by sacdallago** [comment] 2016-06-27 13:49
Everything should be back to normal

**Closed as completed by sacdallago** 2016-06-27 13:49 UTC
