### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectF#19] opened 2016-03-12 12:22 UTC
Somebodey needs to think about the about page, where all the project members will be listed.

**Comment by mammuth** [comment] 2016-03-19 23:59
ToDo:
- [ ] Descriptions
- [ ] Attributions (s. #65 )
- [ ] Contributors data (make them send their data in our schema so we can copy it in)

Contributor-Schema:

```
{
  name: "Member1",
  link: "https://github.com",
  team: "F"
}
note: link is optional
```

**Comment by jorjo1** [comment] 2016-03-21 10:43
@Rostlab/js_cs_sose_2016_students please have a look, let's add all your data here by editing this comment:
(link is optional)

``` javascript
[
{
  name: "Georgi Anastasov",
  link: "https://github.com/jorjo1",
  team: "F"
},
{
  name: "Max Muth",
  link: "http://www.maxi-muth.de",
  team: "F"
},
{
  name: "Florian Gareis",
  link: "https://www.florian-gareis.com",
  img:  "http://gravatar.com/avatar/9c8cef19ae44af5e2ed64addfe701a77",
  team: "E"
},
{
  name: "Christian Dallago",
  link: "http://dallago.us",
  img:  "https://c2.staticflickr.com/2/1481/25418571675_2dbacb53a7_q.jpg",
  team: "Mentor"
},
{
  name: "Kordian Bruck",
  link: "https://bruck.me",
  team: "A"
},
{
  name: "Julien Schmidt",
  link: "https://github.com/julienschmidt",
  team: "D"
},
{
  name: "Jonas Kaltenbach",
  link : "https://github.com/kajo404",
  team : "D"
},
{
name: "Marcus Novotny",
link : "https://github.com/marcusnovotny",
team : "D"
},
{
name: "Michael Legenc",
link : "http://michael.legenc.de",
team : "A"
},
{
name : "Georg Gar",
link : "https://github.com/Hack3l",
team : "B"
},
{
name: "Alexander Beischl",
link: "https://github.com/AlexBeischl",
team: "C"
},
{
name: "Maximilian Bandle",
link: "https://github.com/mbandle",
team: "C"
},
{
name: "Tobias Piffrader",
link: "https://github.com/tPiffrader",
team: "C"
},
{
name: "Yasar Kücükkaya",
link: "http://www.yk-code.de",
team: "F"
},
{
name: "Camille Mainz",
link : "https://github.com/Logarythms",
team : "D"
},
{
name: "Oleksii Moroz",
link: "https://github.com/AlexMoroz",
team: "E"
},
{
name : "Subburam Rajaram",
link : "https://github.com/subburamr",
team : "B"
},
{
name: "Anna Sesselmann",
link: "https://github.com/asesselmann",
team: "B"
},
{
name: "Guy Yachdav",
link: "https://www.linkedin.com/in/gyachdav",
team: "Mentor"
},
{
name: "Santanu Mohanta",
link: "https://github.com/santanumohanta",
team: "D"
},
{
name: "Sohel Mahmud",
link: "https://github.com/docjag",
team: "A"
},
{
    name: "Cavid Salahov",
    link: "https://github.com/CavidSalahov",
    team: "E"
},
{
name: "Nicola De Socio", 
link: "https://github.com/nicoladesocio", 
team: "B"},
{
name: "Thuy Tran",
link: "https://github.com/ThuyNganTran",
team: "B"
},
{
name: "Tatyana Goldberg",
link: "https://rostlab.org/~goldberg/",
team: "Mentor"
},
{
name: "Jonas Ebel",
link: "https://github.com/jonny3576",
team: "E"
},
{
name:"Dat Nguyen",
link:"https://github.com/vanp33",
team:"D"
}
]

```

:exclamation: if you cannot edit this comment, just post your details on this thread :) If you have no webpage or do not want us to show your github acc, just leave it blank. We have got this covered ^^

**Comment by sacdallago** [comment] 2016-03-21 10:50
Which team should I put? :laughing: `ABCDEF`

**Comment by jorjo1** [comment] 2016-03-21 10:57
@sacdallago there is a special place for you!

**Comment by mammuth** [comment] 2016-03-21 10:57
Hm... I'm not sure how I implemented it. 
Maybe It will be like Schrödingers Cat: Either @sacdallago is in the about page, or not. We can't tell right now :wink:

**Comment by sacdallago** [comment] 2016-03-21 11:04
> @sacdallago there is a special place for you!

@jorjo1 I hope that's not a threat :laughing: :smiling_imp:

**Comment by kordianbruck** [comment] 2016-03-21 12:39
Can't edit it, as I'm not a collaborator in this project #fail

**Comment by jorjo1** [comment] 2016-03-21 12:46
@kordianbruck just put your details as a comment on this issue and I carry about that ^^

**Comment by kordianbruck** [comment] 2016-03-21 12:47
```
{
  name: "Kordian Bruck",
  link: "https://bruck.me",
  team: "A"
},
```

**Comment by julienschmidt** [comment] 2016-03-21 12:48
``` js
{
  name: "Julien Schmidt",
  link: "https://github.com/julienschmidt",
  team: "D"
}
```

D4, in case that matters :wink:

**Comment by kajo404** [comment] 2016-03-21 13:34
```
{
name: "Jonas Kaltenbach",
link : "https://github.com/kajo404",
team : "D"
}
```

**Comment by marcusnovotny** [comment] 2016-03-21 14:00
```
{
name: "Marcus Novotny",
link : "https://github.com/marcusnovotny",
team : "D"
}
```

D4

**Comment by ghost** [comment] 2016-03-21 15:28
```
{
name: "Michael Legenc",
link : "http://michael.legenc.de",
team : "A"
}
```

**Comment by Hack3l** [comment] 2016-03-21 16:34
```
{
name : "Georg Gar",
link : "https://github.com/Hack3l",
team : "B"
}
```

**Comment by AlexBeischl** [comment] 2016-03-21 16:54
{
  name: "Alexander Beischl",
  link: "https://github.com/AlexBeischl",
  team: "C"
}

and my team members:

{
  name: "Maximilian Bandle",
  link: "https://github.com/mbandle",
  team: "C"
}

{
  name: "Tobias Piffrader",
  link: "https://github.com/tPiffrader",
  team: "C"
}

**Comment by yashha** [comment] 2016-03-21 17:08
{
name: "Yasar Kücükkaya"
link: "http://www.yk-code.de"
team: "F"
}

**Comment by Logarythms** [comment] 2016-03-21 18:00
{
name: "Camille Mainz",
link : "https://github.com/Logarythms",
team : "D"
}

**Comment by AlexMoroz** [comment] 2016-03-21 19:41
{
name: "Oleksii Moroz",
link: "https://github.com/AlexMoroz",
team: "E"
}

**Comment by subburamr** [comment] 2016-03-21 21:34
{
name : "Subburam Rajaram",
link : "https://github.com/subburamr",
team : "B"
}

**Comment by asesselmann** [comment] 2016-03-21 21:56
{
name: "Anna Sesselmann",
link: "https://github.com/asesselmann",
team: "B"
}

**Comment by sacdallago** [comment] 2016-03-21 21:58
I'm loving this. This is like the perfect method to know: who reads github issues and when :dancer:

**Comment by ghost** [comment] 2016-03-21 23:35
{
name: "Santanu Mohanta",
link: "https://github.com/santanumohanta",
team: "D"
}

**Comment by docjag** [comment] 2016-03-21 23:48
{
name: "Sohel Mahmud",
link: "https://github.com/docjag",
team: "A"
}

**Comment by jsalahov** [comment] 2016-03-22 08:23
``` javascript
{
    name: "Cavid Salahov",
    link: "https://github.com/CavidSalahov",
    team: "E"
}
```

**Comment by nicoladesocio** [comment] 2016-03-22 08:44
`{name: "Nicola De Socio",
link: "https://github.com/nicoladesocio",
team: "B"}`

**Comment by ThuyNganTran** [comment] 2016-03-22 10:37
{
    name: "Thuy Tran",
    link: "https://github.com/ThuyNganTran",
    team: "B"
}

**Comment by goldbergtatyana** [comment] 2016-03-22 10:43
{
name: "Tatyana Goldberg",
link: "https://rostlab.org/~goldberg/",
team: "Mentor"
}

**Comment by jcebel** [comment] 2016-03-22 12:59
{
name: "Jonas Ebel",
link: "https://github.com/jonny3576"
team: "E"
}

**Comment by vanp33** [comment] 2016-03-22 13:09
{
name:"Dat Nguyen",
link:"https://github.com/vanp33",
team:"D"
}

**Comment by julienschmidt** [comment] 2016-03-28 18:46
The English name of TUM is "Technical University **of** Munich" btw
(See https://portal.mytum.de/corporatedesign/index_html/regeln/index_sprachregelung)

**Comment by togiberlin** [comment] 2016-03-28 22:18
{
name: "Togi Dashnyam",
link: "https://github.com/togiberlin"
team: "A"
}

**Comment by theocheslerean** [comment] 2016-03-29 10:16
{
  name: "Theodor Cheslerean Boghiu",
  team: "A"
}

**Comment by boriside** [comment] 2016-03-29 13:33
{
name: "Boris Idesman",
link: "https://github.com/boriside",
team: "A"
}

**Comment by jorjo1** [comment] 2016-03-31 17:59
@Rostlab/js_cs_sose_2016_students :boom: 
Hello everyone, we decided to put photos of yours next to your name in the _About_ page. The image's height will not be bigger than your names' height. 

So please post images here again in this format:
`img: "http://placehold.it/50x50"`
In case you want to keep your photo private, we'll have to take your GitHub pixel image.

Thanks in advance! Please be quick ^^

**Comment by julienschmidt** [comment] 2016-03-31 18:40
Please use neither a photo of me nor my GitHub profile picture.

**Comment by gyachdav** [comment] 2016-04-01 20:21
img: http://1.gravatar.com/avatar/7cbde56ba3b8f244513f710c55721dac

**Comment by gyachdav** [comment] 2016-04-01 20:21
@jorjo1  please assign a deadline for this

**Comment by goldbergtatyana** [comment] 2016-04-02 10:57
JST group picture: https://rostlab.org/~goldberg/JST_Seminar2016.jpg

**Comment by mammuth** [comment] 2016-04-05 19:31
ToDo:
Group picture
Mentors
Front end
Machine learning
Map
Twitter
Database
Keep all in separate row so names will be visible At most have 3 names in one row

**Comment by mammuth** [comment] 2016-04-07 13:35
Assigning to @Andrew094 who is in charge of #234, what's basically the same thing.

**Comment by mammuth** [comment] 2016-04-07 13:43
Actually this issue is a duplicate of #234. 
This one is with a lot of followers; so to stop from spamming on them, I'm going to close this in favor of #234.

PS: the About.jsx in the project is updated with all the contributors, who put their names and groups here.

**Comment by k-angelo** [comment] 2016-04-18 08:28
{
name: "Konstantinos Angelopoulos",
team: "B"
}

**Comment by sacdallago** [comment] 2016-04-18 12:31
@konstantinos-angelo added

**Comment by Emiliyana** [comment] 2016-04-18 15:02
{
name: "Emiliyana Kalinova",
link: "https://github.com/Emiliyana",
team: "E"
}

**Comment by AngeKouemo** [comment] 2016-04-19 14:58
{
  name: "Ange Laure Temzeung Kouemo",
  team: "E"
}

**Comment by theocheslerean** [comment] 2016-04-20 23:05
Hi. Can you change  the link in my name to

{
name: "Theodor Cheslerean Boghiu",
link: "https://de.linkedin.com/in/theodor-cheslerean-boghiu-234511102"
}

Please?

**Comment by sacdallago** [comment] 2016-04-21 09:51
Done all up to here

**Closed as completed by sacdallago** 2016-04-21 09:51 UTC
Labels: prio: low
