### ISSUE TITLE
Headerbar Blocks Searbar 

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectF#439] opened 2016-04-15 08:57 UTC
If you aren't using the full width of the browser-window, the headerbar is laying over the searchbar. Therefore, you can' t use it.
![bildschirmfoto 2016-04-15 um 10 11 21](https://cloud.githubusercontent.com/assets/17533952/14556514/d5859518-02f8-11e6-9900-238d2f5a347e.png)

**Comment by mammuth** [comment] 2016-04-15 08:58
Thanks Alex. 

Closing as duplicate of #427

**Closed as completed by mammuth** 2016-04-15 08:58 UTC
