### ISSUE TITLE
Portal crashes on mobile devices

### ISSUE THREAD

**Issue by boriside** [Rostlab/JS16_ProjectF#339] opened 2016-04-08 20:43 UTC
I test the portal on 3 mobile devices: ipad and two android phones, all with google chrome. From 10 attempts to load the site's home page 2-3 are successful, in the fail cases the browser crashes. This behaviour appeared since the twitter sentiment graphs were added.

**Comment by jorjo1** [comment] 2016-04-08 21:18
http://www.got.show try this. Loads every time for me.
Probably because of Heroku?

**Comment by boriside** [comment] 2016-04-08 21:31
![image](https://cloud.githubusercontent.com/assets/4656678/14398118/081040da-fde2-11e5-94c1-df9bf43de534.png) no..

**Comment by mammuth** [comment] 2016-04-08 21:33
Strange. can't reproduce on latest chrome on Android...

**Comment by jorjo1** [comment] 2016-04-08 21:37
Tested on an older version of iOS and safari works. :heavy_check_mark: 
Tested on Android with newest Chrome :heavy_check_mark:

**Comment by boriside** [comment] 2016-04-08 21:37
Maybe it's only issue on my devices, but I would suggest @Rostlab/js_cs_sose_2016_students to try the portal on mobile device (especially on tablets)

**Comment by boriside** [comment] 2016-04-08 21:39
And one more thing guys, why don't we actually exclude PLODs < ..lets say 20? Maybe we should open another issue on that, but I think they are not so interesting for the people.

**Comment by yashha** [comment] 2016-04-08 21:40
Android Opera :heavy_check_mark: 
But I noticed the map is catching the touch inputs, but thats probably not evitably.

**Comment by mammuth** [comment] 2016-04-08 21:41
Maybe your network is blocking something which causes our app to crash?

Regarding your plod, suggestion: Actually the characters with a low PLOD are the _Survivors_, so probably they make sense.

@yashha, Opera ?!?!?! :flushed:

**Comment by gyachdav** [comment] 2016-04-09 01:31
Tried on Android with newest chrome. seems to work.

**Comment by sacdallago** [comment] 2016-04-09 09:42
iPad mini (safari + chrome), Nexus 7 2013 (chrome), Galaxy Note 4 (chrome, opera mini, samsung internet) work

**Comment by mammuth** [comment] 2016-04-09 09:59
@boriside, could you try it in a different network? Like your mobile network eg. 

Otherwise I think we can close this, since it's not reproducible.

**Closed as completed** 2016-04-09 09:59 UTC
Labels: bug, prio: high
